language: node_js
node_js:
  - "7"
before_script: npm install
script:
  # - npm test
  # - npm run deploy -- --test
  - npm run test:csv
after_success:
  - bash ./bin/deploy.sh
env:
  global:
  - GH_REF: github.com/coderdojo-japan/dojopaas
  - secure: "rlNWiuDVXwFol5DiRJ0bu7PVTITX47jKcx3w8HLiQA/WIgc69ptFEc8oV22ZqIKxL/LDH5idsF5kLM40laY0Gs4g8alFYVvKS1kEpbirUGPNB+f8ynf/Ffj6+aFl+mcazpiizQMBSIJx4rwjPykoISAem8G7y4qr7kfxcZkuQ4cCK2kQc1epNuzCHwpISkEZum2sWUyGDUWvAtAjwr2m8ztATt58eDd/ncOQW+ssgwgRDATYMTuWUPpZkkWfqyd/xTOx6HwRr1hLoGNFL6pLjavWM3L0uRFQs5vMuWScySYeIsrFiSsVnnoDFcycI7bJRiaD8IiVDjMtLU1Xv9Kc/fR5qCavrUYcUgrnckZJLfyY6nPBfSrW3wgSZbkebTEJDNGpMmMx3DtJH/6SaJL62lid1+iEyHWx+3vVqFBFQkvpeiCLhCGPZm3aNQH3ZQBAjGIY4C71ZZwha8iBkstZnnWRQwrkr8b7jggppwNfo0nKSDnW/qZQ+GmK9Klr8k22GSarFt7kVpzwIrcAa6puShXOpYPie38GggbhXu3Fzkko0ASUIYKUC+8VMeMY1Y/jb5qsxECS7sUWRLEsff0eVKQr4i3OFnwzw+LDnido8bNselkUjdfWuGDNXxynSWStysTP81YGoMiinb/H248dh2nQTiGkp2Dl5P6EugPYNOE="
